### ISSUE TITLE
DSchool git repo 

### ISSUE THREAD

**Issue by tafkey** [itminedu/add-repo-instructions#1]
Please add https://git.dschool.edu.gr

**Comment by ellakdev** [comment]
Δεν υπάρχει πρόσβαση σε αυτό το repository: "This space is limited to the team of CTI DIS working for the services of dschool.edu.gr. For any issue, contact support."

**Comment by tafkey** [comment]
Κλείνω το issue ως άκυρο και θα ανοίξω άλλο για κάθε επιμέρους repository ξεχωριστά.
