### ISSUE TITLE
LOM-GR repo

### ISSUE THREAD

**Issue by tafkey** [itminedu/add-repo-instructions#2]
https://git.dschool.edu.gr/photodentro/LOM-GR

**Comment by ellakdev** [comment]
Mirrored at https://github.com/itminedu/LOM-GR

**Comment by tafkey** [comment]
Το repo δεν γίνεται αυτόματα mirrored, δεν εμφανίζονται δηλαδή οι αλλαγές που έγινα τις τελευταίες μέρες στο repo (στο git.dschool.edu.gr).

**Comment by tafkey** [comment]
https://github.com/itminedu/LOM-GR
